services:
  mini-ecommerce.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  redis:
    image: "redis:latest"
    ports:
      - "6279:6379"
    command: redis-server --requirepass Binhpzo213@gmail.com
    volumes:
      - redis_data:/data

  pg:
    image: "postgres:17"
    container_name: postgres_db_mini_ecommerce
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_123
      POSTGRES_DB: mini-ecommerce
    ports:
      - "5469:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 


volumes:
  redis_data: 
  db_data: